language: clojure
lein: lein2
script: lein install && lein test
notifications:
  slack:
    secure: YW9fccvdE7QSjJ3bmPzJAeXbK+bJPy4kyeUIigTAg5+Kz8kBbbahBuDfp226MoAKCLCluckwVyutE+9AILyvRHRyx/Mnyh9Mgfh9UUCiLYl9gT9NxoB5oXMOy6Wtjg7Dd9yZieNM93tCN2ivDclk+SmQtZMcwKzbSY4UUzwMW0+eCLB1NOuC9qmvwbJjkPzTjN8gS64RCsOsy2ne5hfljVMJtLq9ODhZwnUkIurhRYHeFkqB8gcKbLwLvPbxYspSF8OMoTyCzOt0vuCSkboLorCtOttmbSCCn1Xe6g8YBrbDRkPUJAC1Jb4IEeubjjl5yq7so03Quz8oeFVR4MYa7y849sVEj7KQccPcsM24s+kg6OWqWlx8AiVr+xnTfvJkOAMRGGIsrGQ9rMigRunPzoTFDeX6sed5xWOV/zkqd0nWo3EQFlMX1Lpmzr7NMMTo2N+l3N+FOpo2is2FRHBvOxYjptLojeSivuVfdUkAdjvwrcAGu99w0aWhz/xWVNvl6huYIuvncZc/nsDJQ8bOr767HtDb5NDOs7mSfoiKpFLV+clwWq85Tft3asvulyHNo7Q+wn97SyVaJhlAb4tbNpF895R/+3F2hw+GL0iwjiiLDge/CXUX8s4U1ytJyaq2e9GGWBrDSSaONQYt5vVBfTiEiRLyoxvesNHyBQ3pQl4=
deploy:
  provider: heroku
  api_key:
    secure: Jf3nb8/tGvidpyG4OHyfGoQypEDHUhCOvfz8U16FfTe9umEHLFzkX1egLLI2hw3bvX4L+9ECk/pW+GCyLzOJdYUgvkh2kRfb0fquTO99hqw1AVeGbFsHOFwtexJkfc+NK9S1Kv0DeZeAWW7NrTjIQYoi9ZCoKX2QuuIzWacGfDTPTtN7/WWeaKnRZrwib4yE1fin4qkhayZyB7BByUMIe7iCvt7JPcLa8zHst3d+Nx+k2Y58JHeIrMk1O44w6TMQcG4XNrai5fsKSvwMxHZk/eKvC3fpWsfXyPIMNicEdqjEFe4eFT1eWMaODZAPes4ZHto14pM6L+NIjcLIgzoPX95sUVzzopo0+BlbRg2jG0af4L8KA7gjZKfQ+HTbkGwkCxlTRtQ3kReKVGEOIWLYVh3xsGJQ2cQFSgnTWO1iH54Ecjyr6ZSokxn1mfKRIbrRotQU+IG+znTTPHAG5jSxnDnosQy9iFVtkccGuT8oVYIHOhyfP+27Kk0u5pziTkCyp3NLlTQ5bAtmFH/f0Bd7673Gy6ezjgefHyFk0gO5lL9ShEoN/pYoDdgBJuWXliRDYr8ebkmrCS4k1POm/KA7AKEdakJWRUeLD3kgqwzDqz8uoXHmU6oWVfV6vTTkoN6DCIad2eIsLaK76257dmUcqNun4yrjBUz8A5KNUDNjavo=
  app: peaceful-sierra-20433
  on:
    repo: numerry/prototype


