#!/bin/sh

lein uberjar
scp target/uberjar/numerry.jar $NUMERRY_SSH:$NUMERRY_HOME/numerry.jar
ssh $NUMERRY_SSH sudo cp $NUMERRY_HOME/numerry.jar /var/numerry/numerry.jar
ssh $NUMERRY_SSH sudo service numerry restart

