#!/bin/sh

lein uberjar
scp target/uberjar/numerry.jar numerry:$NUMERRY_HOME/numerry.jar
ssh numerry sudo cp $NUMERRY_HOME/numerry.jar /var/numerry/numerry.jar
ssh numerry sudo service numerry restart

